'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PreferredPowerModeEqualsBalanced() As Boolean
            Get
                Return CType(Me("PreferredPowerModeEqualsBalanced"),Boolean)
            End Get
            Set
                Me("PreferredPowerModeEqualsBalanced") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property GamingPowerModeEquals70Freq() As Boolean
            Get
                Return CType(Me("GamingPowerModeEquals70Freq"),Boolean)
            End Get
            Set
                Me("GamingPowerModeEquals70Freq") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CheckInvertalEqualsFrequent() As Boolean
            Get
                Return CType(Me("CheckInvertalEqualsFrequent"),Boolean)
            End Get
            Set
                Me("CheckInvertalEqualsFrequent") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GTA5")>  _
        Public Property TargetProcess() As String
            Get
                Return CType(Me("TargetProcess"),String)
            End Get
            Set
                Me("TargetProcess") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property StartOnBootEnabled() As Boolean
            Get
                Return CType(Me("StartOnBootEnabled"),Boolean)
            End Get
            Set
                Me("StartOnBootEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property StartMinimized() As Boolean
            Get
                Return CType(Me("StartMinimized"),Boolean)
            End Get
            Set
                Me("StartMinimized") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property TopMost() As Boolean
            Get
                Return CType(Me("TopMost"),Boolean)
            End Get
            Set
                Me("TopMost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AutoPilotEnabled() As Boolean
            Get
                Return CType(Me("AutoPilotEnabled"),Boolean)
            End Get
            Set
                Me("AutoPilotEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CoreEngineModeEqualsOptimized() As Boolean
            Get
                Return CType(Me("CoreEngineModeEqualsOptimized"),Boolean)
            End Get
            Set
                Me("CoreEngineModeEqualsOptimized") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ca366f9a-4ace-4337-b948-5b196e337c7d")>  _
        Public Property LowFreqGUID() As String
            Get
                Return CType(Me("LowFreqGUID"),String)
            End Get
            Set
                Me("LowFreqGUID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property FirstTimeClosing() As Boolean
            Get
                Return CType(Me("FirstTimeClosing"),Boolean)
            End Get
            Set
                Me("FirstTimeClosing") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UserTrackingEnabled() As Boolean
            Get
                Return CType(Me("UserTrackingEnabled"),Boolean)
            End Get
            Set
                Me("UserTrackingEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property TaskManagerEnabled() As Boolean
            Get
                Return CType(Me("TaskManagerEnabled"),Boolean)
            End Get
            Set
                Me("TaskManagerEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property TaskManagerWarningRemoved() As Boolean
            Get
                Return CType(Me("TaskManagerWarningRemoved"),Boolean)
            End Get
            Set
                Me("TaskManagerWarningRemoved") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property TaskManagerRestartAfterSession() As Boolean
            Get
                Return CType(Me("TaskManagerRestartAfterSession"),Boolean)
            End Get
            Set
                Me("TaskManagerRestartAfterSession") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BootManagerEnabled() As Boolean
            Get
                Return CType(Me("BootManagerEnabled"),Boolean)
            End Get
            Set
                Me("BootManagerEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NoImpactEnabled() As Boolean
            Get
                Return CType(Me("NoImpactEnabled"),Boolean)
            End Get
            Set
                Me("NoImpactEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property TaskManagerPrioritize() As Boolean
            Get
                Return CType(Me("TaskManagerPrioritize"),Boolean)
            End Get
            Set
                Me("TaskManagerPrioritize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EnableExperimentalFeatures() As Boolean
            Get
                Return CType(Me("EnableExperimentalFeatures"),Boolean)
            End Get
            Set
                Me("EnableExperimentalFeatures") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LegacySetting")>  _
        Public Property TrackU() As String
            Get
                Return CType(Me("TrackU"),String)
            End Get
            Set
                Me("TrackU") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ApplicationStatupMesurementValue1() As String
            Get
                Return CType(Me("ApplicationStatupMesurementValue1"),String)
            End Get
            Set
                Me("ApplicationStatupMesurementValue1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ApplicationStatupMesurementValue2() As String
            Get
                Return CType(Me("ApplicationStatupMesurementValue2"),String)
            End Get
            Set
                Me("ApplicationStatupMesurementValue2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DisableCoreForm() As Boolean
            Get
                Return CType(Me("DisableCoreForm"),Boolean)
            End Get
            Set
                Me("DisableCoreForm") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property GroupPolicyForceAutoPilot() As Boolean
            Get
                Return CType(Me("GroupPolicyForceAutoPilot"),Boolean)
            End Get
            Set
                Me("GroupPolicyForceAutoPilot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DisableLegacyServices() As Boolean
            Get
                Return CType(Me("DisableLegacyServices"),Boolean)
            End Get
            Set
                Me("DisableLegacyServices") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GTA5")>  _
        Public Property DefaultTargetProcess() As String
            Get
                Return CType(Me("DefaultTargetProcess"),String)
            End Get
            Set
                Me("DefaultTargetProcess") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property PreferredCPUModeAsByte() As Byte
            Get
                Return CType(Me("PreferredCPUModeAsByte"),Byte)
            End Get
            Set
                Me("PreferredCPUModeAsByte") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AllowPowermodeControl() As Boolean
            Get
                Return CType(Me("AllowPowermodeControl"),Boolean)
            End Get
            Set
                Me("AllowPowermodeControl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DisableDeveloperDetectorService() As Boolean
            Get
                Return CType(Me("DisableDeveloperDetectorService"),Boolean)
            End Get
            Set
                Me("DisableDeveloperDetectorService") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("IDLE")>  _
        Public Property ApplicationSELFPriority() As String
            Get
                Return CType(Me("ApplicationSELFPriority"),String)
            End Get
            Set
                Me("ApplicationSELFPriority") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DisableLegacyCheckboxStyleDetectionSystem() As Boolean
            Get
                Return CType(Me("DisableLegacyCheckboxStyleDetectionSystem"),Boolean)
            End Get
            Set
                Me("DisableLegacyCheckboxStyleDetectionSystem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UserPreferencesModule")>  _
        Public Property DEBUG_StartingForm() As String
            Get
                Return CType(Me("DEBUG_StartingForm"),String)
            End Get
            Set
                Me("DEBUG_StartingForm") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DisableSizeChangedEventChecks() As Boolean
            Get
                Return CType(Me("DisableSizeChangedEventChecks"),Boolean)
            End Get
            Set
                Me("DisableSizeChangedEventChecks") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("180")>  _
        Public Property UI_DefaultHeight() As Integer
            Get
                Return CType(Me("UI_DefaultHeight"),Integer)
            End Get
            Set
                Me("UI_DefaultHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("313")>  _
        Public Property UI_DefaultWidth() As Integer
            Get
                Return CType(Me("UI_DefaultWidth"),Integer)
            End Get
            Set
                Me("UI_DefaultWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1750")>  _
        Public Property CheckPowerPlanInterval() As Integer
            Get
                Return CType(Me("CheckPowerPlanInterval"),Integer)
            End Get
            Set
                Me("CheckPowerPlanInterval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property FastCheckConditionCheckPowerModeEngineInterval() As String
            Get
                Return CType(Me("FastCheckConditionCheckPowerModeEngineInterval"),String)
            End Get
            Set
                Me("FastCheckConditionCheckPowerModeEngineInterval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property RedirectConsoleToFile() As Boolean
            Get
                Return CType(Me("RedirectConsoleToFile"),Boolean)
            End Get
            Set
                Me("RedirectConsoleToFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property FlushConsoleAtStartup() As Boolean
            Get
                Return CType(Me("FlushConsoleAtStartup"),Boolean)
            End Get
            Set
                Me("FlushConsoleAtStartup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Balanced")>  _
        Public Property LastCpuModeFriendlyName() As String
            Get
                Return CType(Me("LastCpuModeFriendlyName"),String)
            End Get
            Set
                Me("LastCpuModeFriendlyName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AllowQuit() As Boolean
            Get
                Return CType(Me("AllowQuit"),Boolean)
            End Get
            Set
                Me("AllowQuit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("529")>  _
        Public Property UI_MaxHeight() As String
            Get
                Return CType(Me("UI_MaxHeight"),String)
            End Get
            Set
                Me("UI_MaxHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("316")>  _
        Public Property UI_MaxWidth() As String
            Get
                Return CType(Me("UI_MaxWidth"),String)
            End Get
            Set
                Me("UI_MaxWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("180")>  _
        Public Property UI_MinHeight() As String
            Get
                Return CType(Me("UI_MinHeight"),String)
            End Get
            Set
                Me("UI_MinHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SafemodeEnabled() As Boolean
            Get
                Return CType(Me("SafemodeEnabled"),Boolean)
            End Get
            Set
                Me("SafemodeEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("This is where all the application settings stored. You may manually override any "& _ 
            "value but changing values may cause application to crash or have serious issues."& _ 
            " Proceed with caution. Before changing any values, please make sure the APMS app"& _ 
            "lication has quit. ")>  _
        Public Property AboutThisFile() As String
            Get
                Return CType(Me("AboutThisFile"),String)
            End Get
            Set
                Me("AboutThisFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property enableGameDetection() As Boolean
            Get
                Return CType(Me("enableGameDetection"),Boolean)
            End Get
            Set
                Me("enableGameDetection") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.AutoPowerModeSwitcher.My.MySettings
            Get
                Return Global.AutoPowerModeSwitcher.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
