// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


using System.Diagnostics;
using System.Drawing;
using Microsoft.VisualBasic;

namespace AutoPowerModeSwitcher.My.Resources
{

    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [HideModuleName()]
    internal static class Resources
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("AutoPowerModeSwitcher.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon AppIcon
        {
            get
            {
                var obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return (Icon)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon ApplicationNewIconBlue
        {
            get
            {
                var obj = ResourceManager.GetObject("ApplicationNewIconBlue", resourceCulture);
                return (Icon)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon ApplicationNewIconPurple
        {
            get
            {
                var obj = ResourceManager.GetObject("ApplicationNewIconPurple", resourceCulture);
                return (Icon)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon ApplicationNewIconWhite
        {
            get
            {
                var obj = ResourceManager.GetObject("ApplicationNewIconWhite", resourceCulture);
                return (Icon)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap CryptedBytesLogo
        {
            get
            {
                var obj = ResourceManager.GetObject("CryptedBytesLogo", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap KTnby6jTq
        {
            get
            {
                var obj = ResourceManager.GetObject("KTnby6jTq", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon NotifyIcon_balanced
        {
            get
            {
                var obj = ResourceManager.GetObject("NotifyIcon_balanced", resourceCulture);
                return (Icon)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon NotifyIcon_cpu22
        {
            get
            {
                var obj = ResourceManager.GetObject("NotifyIcon_cpu22", resourceCulture);
                return (Icon)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon NotifyIcon_error
        {
            get
            {
                var obj = ResourceManager.GetObject("NotifyIcon_error", resourceCulture);
                return (Icon)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon NotifyIcon_HighPerformance
        {
            get
            {
                var obj = ResourceManager.GetObject("NotifyIcon_HighPerformance", resourceCulture);
                return (Icon)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon NotifyIcon_PowerSaver
        {
            get
            {
                var obj = ResourceManager.GetObject("NotifyIcon_PowerSaver", resourceCulture);
                return (Icon)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap tumblr_inline_np9hcuZr931qd3uu5_540
        {
            get
            {
                var obj = ResourceManager.GetObject("tumblr_inline_np9hcuZr931qd3uu5_540", resourceCulture);
                return (Bitmap)obj;
            }
        }
    }
}